version: "3.9"
services:
  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: habit_tracker
      MYSQL_USER: docker
      MYSQL_USER_PASSWORD: admin123
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - erick-network
  habit-tracker:
    image: kleimerick/habilt-tracker
    build: .
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/habit_tracker?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.NAME: root
      SPRING.DATASOURCE.PASSWORD: admin123
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - erick-network
networks:
  erick-network:
    driver: bridge
    
   
    
    

